import datetime

extensions = [
    'recommonmark',

    # Auto-generate section labels.
    'sphinx.ext.autosectionlabel'
]

source_suffix = ['.md']

# Prefix document path to section labels, otherwise autogenerated labels would look like 'heading'
# rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True

copyright = f'2019-{datetime.date.today().year}, Kael Zhang<i@kael.me> and contributors'

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'alabaster'

